language: node_js

node_js:
  - 7
  - 6

script: npm test

services:
  - postgresql

before_script:
  - yarn
  - dropdb --if-exists docmanapi_test && createdb docmanapi_test
  - npm run db:migrate:test

after_success:
    - npm run coveralls
    - node node_modules/codeclimate-test-reporter/bin/codeclimate < coverage/lcov.info
