language: node_js

node_js:
  - 7
  - 6

script: npm test

services:
  - postgresql

before_script:
  - yarn install
  - dropdb --if-exists docmanapi_test && createdb docmanapi_test
  - NODE_ENV=test npm run test_db_migrate

after_success:
    - npm run coveralls
    - node node_modules/codeclimate-test-reporter/bin/codeclimate < coverage/lcov.info
