language: node_js
node_js:
  - "6"
script: npm test

services:
  - postgresql

before_script:
  - yarn
  - dropdb --if-exists docmanapi_test && createdb docmanapi_test
  - npm run test_db_migrate

after_success:
    - npm run coveralls
    - node node_modules/codeclimate-test-reporter/bin/codeclimate < coverage/lcov.info
