language: node_js
before_install:
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - yarn install

cache: yarn

node_js:
  - 7
  - 6
script: npm test

services:
  - postgresql

before_script:
  - npm install
  - dropdb --if-exists docmanapi_test && createdb docmanapi_test
  - npm run test_db_migrate

after_success:
    - npm run coveralls
    - node node_modules/codeclimate-test-reporter/bin/codeclimate < coverage/lcov.info
