language: node_js
node_js:
  - "6"
script: npm test

before_script: 
    - yarn

addons:
  code_climate:
    repo_token: <token>

after_success:
    - npm run coveralls
    - node node_modules/codeclimate-test-reporter/bin/codeclimate < coverage/lcov.info