language: node_js

node_js:
  - 6

script: npm run coveralls

services:
  - postgresql

before_script:
  - yarn install
  - dropdb --if-exists docmanapi_test && createdb docmanapi_test
  - NODE_ENV=test npm run test_db_migrate

# after_success:
#     - npm run coveralls
